### ISSUE TITLE
Attribute Error on layer or folder export

### ISSUE THREAD

**Issue by Jose-Moreno** [GDQuest/krita-batch-exporter#46]
**I'm submitting a...**

- [X] Bug report.
- [ ] Feature request.

## Bug report ##

**What is the current behavior?**
Exporting a single folder with three layers raises an `AttributeError`

_Note_: Even exporting a single layer fails.

**What is the expected behavior?**
A folder composition should be exported properly as a merged image.

**Tell us the steps to reproduce the bug, and if possible share a minimal demo of the problem.** 

To reproduce my exact document follow these steps:

1. Create a new krita document
2. Create a new folder
3. Add 3 layers and name them 
    + Name doesn't seem to matter for this bug, but for reference inner layers have compound names e.g `"Layer31 0 1 STROKES"`
4. select the folder
5. add the e=png metada to folder only
6. press `Selected Layers` button in `Export` section
7. Get error

## Other ##

**Other information** 

**OS Version** Windows 10 Pro v1909 Build 18363.900
**Krita Version** 4.3.0 (happens with 4.2.8 as well)
**Python Version** 3.8.1
Canvas is 3943 x 3071

Krita's backtrace log
```
AttributeError
Python 3.8.1: E:\Downloads\Software\Design Apps\krita-x64-4.3.0\bin\krita.exe
Thu Jun 25 16:05:53 2020

A problem occurred in a Python script.  Here is the sequence of
function calls leading up to the error, in the order they occurred.

 C:\Users\Neobits\AppData\Roaming\krita\pykrita\batch_exporter\batch_exporter.py in exportSelectedLayers(cfg={'delimiters': OrderedDict([('assign', '='), ('separator', ',')]), 'done': {'msg': 'DONE: {}', 'timeout': 5000}, 'error': {'msg': 'ERROR: {}', 'timeout': 8000}, 'meta': {'c': [''], 'e': ['png'], 'm': [0], 'p': [''], 's': [100], 't': ['']}, 'outDir': 'export', 'rootPat': re.compile('root'), 'sym': re.compile('[^a-zA-Z0-9_-]')}, statusBar=<PyQt5.QtWidgets.QStatusBar object>)
   62         it = map(partial(WNode, cfg), nodes)
   63         it = map(partial(flip(WNode.save), dirName), it)
   64         kickstart(it)
   65     except ValueError as e:
   66         msg, timeout = cfg["error"]["msg"].format(e), cfg["error"]["timeout"]
global kickstart = <function kickstart>
it = <map object>

 C:\Users\Neobits\AppData\Roaming\krita\pykrita\batch_exporter\Utils\__init__.py in kickstart(it=<map object>)
    5     return lambda *a: f(*reversed(a))
    6 
    7 
    8 def kickstart(it):
    9     deque(it, maxlen=0)
global deque = <class 'collections.deque'>
it = <map object>
maxlen undefined

 C:\Users\Neobits\AppData\Roaming\krita\pykrita\batch_exporter\Utils\__init__.py in <lambda>(*a=('E:/FWork/Company/Client/Project/My_Project/ARTE/RECURSOS/map_export', <batch_exporter.Infrastructure.WNode object>))
    3 
    4 def flip(f):
    5     return lambda *a: f(*reversed(a))
    6 
    7 
a = ('E:/FWork/Company/Client/Project/My_Project/ARTE/RECURSOS/ARTE/RECURSOS/map_export', <batch_exporter.Infrastructure.WNode object>)
f = <function WNode.save>
builtinreversed = <class 'reversed'>

 C:\Users\Neobits\AppData\Roaming\krita\pykrita\batch_exporter\Infrastructure.py in save(self=<batch_exporter.Infrastructure.WNode object>, dirname='E:/FWork/Company/Client/Project/My_Project/ARTE/RECURSOS/ARTE/RECURSOS/map_export')
  251         processes the image, names it based on metadata, and saves the image to the disk.
  252         """
  253         img = nodeToImage(self)
  254         meta = self.meta
  255         margin, scale = meta["m"], meta["s"]
img undefined
global nodeToImage = <function nodeToImage>
self = <batch_exporter.Infrastructure.WNode object>

 C:\Users\Neobits\AppData\Roaming\krita\pykrita\batch_exporter\Infrastructure.py in nodeToImage(wnode=<batch_exporter.Infrastructure.WNode object>)
   21     """
   22     SRGB_PROFILE = "sRGB-elle-V2-srgbtrc.icc"
   23     if wnode.trim == False:
   24         bounds = KI.activeDocument().bounds()
   25         x = bounds.x()
wnode = <batch_exporter.Infrastructure.WNode object>
wnode.trim undefined

 C:\Users\Neobits\AppData\Roaming\krita\pykrita\batch_exporter\Infrastructure.py in trim(self=<batch_exporter.Infrastructure.WNode object>)
  114     @property
  115     def trim(self):
  116         if self.meta["t"].lower() in ["false", "no"]:
  117             return False
  118         else:
self = <batch_exporter.Infrastructure.WNode object>
self.meta = OrderedDict([('e', ['png']), ('c', ['']), ('m', [0]), ('p', ['']), ('s', [100]), ('t', [''])])
].lower undefined
AttributeError: 'list' object has no attribute 'lower'
    __cause__ = None
    __class__ = <class 'AttributeError'>
    __context__ = None
    __delattr__ = <method-wrapper '__delattr__' of AttributeError object>
    __dict__ = {}
    __dir__ = <built-in method __dir__ of AttributeError object>
    __doc__ = 'Attribute not found.'
    __eq__ = <method-wrapper '__eq__' of AttributeError object>
    __format__ = <built-in method __format__ of AttributeError object>
    __ge__ = <method-wrapper '__ge__' of AttributeError object>
    __getattribute__ = <method-wrapper '__getattribute__' of AttributeError object>
    __gt__ = <method-wrapper '__gt__' of AttributeError object>
    __hash__ = <method-wrapper '__hash__' of AttributeError object>
    __init__ = <method-wrapper '__init__' of AttributeError object>
    __init_subclass__ = <built-in method __init_subclass__ of type object>
    __le__ = <method-wrapper '__le__' of AttributeError object>
    __lt__ = <method-wrapper '__lt__' of AttributeError object>
    __ne__ = <method-wrapper '__ne__' of AttributeError object>
    __new__ = <built-in method __new__ of type object>
    __reduce__ = <built-in method __reduce__ of AttributeError object>
    __reduce_ex__ = <built-in method __reduce_ex__ of AttributeError object>
    __repr__ = <method-wrapper '__repr__' of AttributeError object>
    __setattr__ = <method-wrapper '__setattr__' of AttributeError object>
    __setstate__ = <built-in method __setstate__ of AttributeError object>
    __sizeof__ = <built-in method __sizeof__ of AttributeError object>
    __str__ = <method-wrapper '__str__' of AttributeError object>
    __subclasshook__ = <built-in method __subclasshook__ of type object>
    __suppress_context__ = False
    __traceback__ = <traceback object>
    args = ("'list' object has no attribute 'lower'",)
    with_traceback = <built-in method with_traceback of AttributeError object>

The above is a description of an error in a Python program.  Here is
the original traceback:

Traceback (most recent call last):
  File "C:\Users\Neobits\AppData\Roaming\krita\pykrita\batch_exporter\batch_exporter.py", line 64, in exportSelectedLayers
    kickstart(it)
  File "C:\Users\Neobits\AppData\Roaming\krita\pykrita\batch_exporter\Utils\__init__.py", line 9, in kickstart
    deque(it, maxlen=0)
  File "C:\Users\Neobits\AppData\Roaming\krita\pykrita\batch_exporter\Utils\__init__.py", line 5, in <lambda>
    return lambda *a: f(*reversed(a))
  File "C:\Users\Neobits\AppData\Roaming\krita\pykrita\batch_exporter\Infrastructure.py", line 253, in save
    img = nodeToImage(self)
  File "C:\Users\Neobits\AppData\Roaming\krita\pykrita\batch_exporter\Infrastructure.py", line 23, in nodeToImage
    if wnode.trim == False:
  File "C:\Users\Neobits\AppData\Roaming\krita\pykrita\batch_exporter\Infrastructure.py", line 116, in trim
    if self.meta["t"].lower() in ["false", "no"]:
AttributeError: 'list' object has no attribute 'lower'
```

**Comment by hhhmmmmmm** [comment]
I had this error. I did the Manual installation process. That, somehow, resulted in two Batch Exporters showing up under Configure Krita > Python Plugin Manager. Which somehow resulted in this exact error. To fix, I deleted the batch exporter .desktop file and its folder in .../roaming/krita/pykrita. As a result, the duplicate Batch Exporter amazingly went away and even more amazingly somehow still works even though there's nothing at all in pykrita folder.

**Comment by NathanLovato** [comment]
Ah, we contributed the add-on to Krita for the last version. I have to check if it's working out of the box here too, and update the instructions accordingly. Thanks for the heads up. I haven't had much time to work on this project as of late

**Comment by hhhmmmmmm** [comment]
You mean it's a candidate for 4.3.2? or 4.4? That's exciting! This extension looks very promising for alleviating a sore spot in the workflow. 

I was testing on 4.3.1 btw. Reverted to 4.3.0 to see if it worked there, but no luck either. Basic exporting was working, but I was never able to get t=no / t=false false to work, which perhaps makes sense because the error above is from the trim.

Do you recommend just waiting for the next alpha or two? Or is their update schedule slower than that?

**Comment by NathanLovato** [comment]
The `t=false` option may not be in the version included in Krita. I'll have to check.

**Comment by hhhmmmmmm** [comment]
For my use case, that's an important feature because I need to export different layers that must be kept exactly in parallel, e.g. albedo and emissive.
